@startuml

!include ./src/Base.puml
!include ./src/Evidences.puml
!include ./src/Participant.puml
!include ./src/Role.puml

Role3rdSys(WeChat, "WeChat Pay")


Party(注册用户1, "注册用户")
Party(注册用户2, "注册用户")
Party(注册用户3, "注册用户")
Party(注册用户4, "注册用户")
Party(注册用户5, "注册用户")
Party(注册用户6, "注册用户")

Party(平台1, "平台")
Party(平台2, "平台")


RoleParty("出租方1", "出租方")
RoleParty("出租方2", "出租方")
RoleParty("出租方3", "出租方")
RoleParty("出租方4", "出租方")


RoleParty("求租方1", "求租方")
RoleParty("求租方2", "求租方")



Rfp(推广服务购买请求, "推广服务购买请求")
Proposal(平台报价, "平台报价", , "amount \n created_at")
Contract(房源推广合同, "房源推广合同")
Fr(房源推广请求, "房源推广请求")
Fc(房源推广确认, "房源推广确认")
Fr(房源推广支付请求,"房源推广支付请求")
Fc(房源推广支付确认,"房源推广支付确认")


'  hree is relationship
Rel_D_dashed(注册用户1, 出租方1, " ")
Ass_L(出租方1, 推广服务购买请求, "1 : N")
Ass_L(推广服务购买请求, 平台报价, "1 : 1")
Ass_D(平台报价, 房源推广合同, "1 : 1")


Ass_D(房源推广合同, 房源推广请求, "1 : 1")
Ass_D(房源推广请求, 房源推广确认, "1 : 1")

Ass_R(房源推广合同, 房源推广支付请求, "1 : N")
Ass_R(房源推广支付请求, 房源推广支付确认, "1 : 1")

Ass_U(出租方2, 房源推广支付确认, "1 : 1")
Ass_R(房源推广请求, 出租方2, "1 : N")

Ass_L(WeChat, 房源推广支付确认, "1 : 1")
Ass_L(平台1, 房源推广确认, "1 : N ")
Ass_U(平台1, 房源推广支付请求, "N : 1")
Rel_L_dashed(注册用户2, 出租方2, " ")






' another context
Rfp(出租房源发布请求, "出租房源发布请求")
Proposal(出租房源审核响应,"出租房源审核响应")
Contract(出租房源发布合同, "出租房源发布合同")
Fr(出租房源发布审核通过请求, "出租房源发布审核通过请求")
Fc(出租房源发布审核通过确认, "出租房源发布审核通过确认")
Fr(出租房源下架请求, "出租房源下架请求")
Fc(出租房源下架确认, "出租房源下架确认")

'  relationship
Rel_D_dashed(注册用户3, 出租方3, " ")
Ass_D(出租方3, 出租房源发布请求, "1 : N")
Ass_D(出租房源发布请求, 出租房源审核响应, "1 : 1")
Ass_D(出租房源审核响应, 出租房源发布合同, "1 : 1")


Ass_D(出租房源发布合同, 出租房源发布审核通过请求, "1 : 1")
Ass_D(出租房源发布审核通过请求, 出租房源发布审核通过确认, "1 : 1")
Ass_R(出租房源发布审核通过请求, 平台2, "N : 1")

Ass_L(出租方4, 出租房源发布审核通过确认, "1 : N ")
Rel_U_dashed(注册用户4, 出租方4, " ")


Ass_R(出租房源发布合同, 出租房源下架请求, "1 : 1")
Ass_R(出租房源下架请求, 出租房源下架确认, "1 : 1")

Ass_U(出租方4, 出租房源下架请求, "1 : N")
Ass_D(出租房源下架确认, 平台2, "1 : N")


Rfp(求租房源发布请求, "求租房源发布请求")
Proposal(求租房源审核响应,"求租房源审核响应")
Contract(求租房源发布合同, "求租房源发布合同")
Fr(求租审核通过确认请求, "求租审核通过确认请求")
Fc(求租审核通过确认, "求租审核通过确认")


Rel_D_dashed(注册用户5, 求租方1, " ")
Ass_D(求租方1, 求租房源发布请求, "1 : N")
Ass_D(求租房源发布请求, 求租房源审核响应, "1 : 1")
Ass_D(求租房源审核响应, 求租房源发布合同, "1 : 1")
Ass_D(求租房源发布合同, 求租审核通过确认请求, "1 : 1")
Ass_D(求租审核通过确认请求, 求租审核通过确认, "1 : 1")

Ass_U(求租方2, 求租审核通过确认, "1 : N")
Rel_U_dashed(注册用户6, 求租方2, " ")



@enduml