!include ./src/Base.puml
!include ./src/Evidences.puml
!include ./src/Participant.puml
!include ./src/Role.puml

' Rfp(app)
' Proposal(customer_service)
' Contract(message_bus)
' Fr(reporting_service)
' Fc(audit_service)
' Party(party, "Party")
' Thing(thing, "Thing")
' Place(place, "Place")
' RoleParty(ptrole, "Audit Store")
' Role3rdSys(third_sys, "Audit Store")
' RoleEvidence(evidence_role, "Audit Store")
Role3rdSys(WeChat, "WeChat Pay")

RoleParty(平台管理员, "平台管理员")
' Place(网站, "网站")
RoleParty(appUser, "appUser")

RoleParty(发布的信息, "发布的信息")


Party(房东, "房东")
Party(中介, "中介")
Party(租客, "租客")
' Proposal(住房信息, "住房信息")
' Proposal(求租信息, "求租信息")
' Thing(会员, "会员")

Boundary(vipOrder, "信息置顶服务") {
    RoleDomain(价格计算器, "价格计算器")
    Proposal(置顶服务定价, "置顶服务定价", "price")
    Contract(信息发布置顶服务, "信息发布置顶服务", "", "amount")
    Contract(推广服务订单, "推广服务订单", "total_price")
    Fr(购买置顶服务, "购买置顶服务", "", "start_at\n expired_at")
    RoleEvidence(订单支付凭证, "订单支付凭证", "paid_at","amount")
}

Boundary(vipService, "推广服务") {
    Proposal(置顶服务申请, "置顶服务申请")
    Contract(置顶服务合约, "置顶服务合约")
    Fr(收到置顶服务规则, "收到置顶服务规则")
    Fc(置顶策略确认单, "置顶策略确认单")
    ' Fr(设置自动刷新服务, "设置自动刷新服务")
    ' Fc(自动刷新服务, "自动刷新服务")
}

Boundary(info, "信息发布服务") {
    Proposal(发布房屋信息申请, "发布房屋信息申请")
    Contract(房屋信息发布规范, "房屋信息发布规范")
    Fr(审核发布信息, "审核发布信息")
    Fc(展示房屋信息, "展示房屋信息")
    Fc(驳回房屋信息, "驳回房屋信息")
}


LAYOUT_TOP_DOWN()

Lay_D(appUser, vipOrder)
Lay_D(appUser, info)

Rel_D_dashed(房东, appUser, " ")
Rel_D_dashed(中介, appUser, " ")
Rel_D_dashed(租客, appUser, " ")

Lay_U(appUser, info)

Rel_U_dashed(appUser, 发布房屋信息申请, "1 : 1")
Rel_D(发布房屋信息申请, 房屋信息发布规范, "N : 1")
Rel_R(房屋信息发布规范, 审核发布信息, "1 : 1")
Rel_D(审核发布信息, 展示房屋信息, "1 : 1")
Rel_U(审核发布信息, 驳回房屋信息, "1 : 1")


Rel_D_dashed(平台管理员, 置顶服务定价, "1 : 1")
Rel_U_dashed(价格计算器, 信息发布置顶服务, "1 : 1")
Rel_U_dashed(appUser, 推广服务订单, "1 : N")

Rel_D(置顶服务定价, 信息发布置顶服务, "1 : 1")
Rel_L(信息发布置顶服务, 推广服务订单, "N : 1")
Rel_D(推广服务订单, 购买置顶服务, "1 : 1")
Rel_D(购买置顶服务, 订单支付凭证, "1 : 1")

Rel_R_dashed(appUser, 购买置顶服务, "1 : 1")

Rel_R_dashed(购买置顶服务, WeChat, "1 : 1")
Rel_D_dashed(WeChat, 订单支付凭证, "1 : 1")
Lay_L(订单支付凭证, WeChat)
' Lay_L(会员, 订单支付凭证)

' Rel_R_dashed(订单支付凭证, 会员, "1 : 1")
Rel_D_dashed( 置顶服务申请,订单支付凭证, "1 : 1")
Rel_D_dashed( 展示房屋信息,发布的信息, "1 : 1")
Rel_D_dashed( 发布的信息,置顶服务申请, "1 : 1")
Rel_D_dashed(appUser, 置顶服务申请, "1 : 1")
Rel_R(置顶服务申请, 置顶服务合约, "1 : 1")
Rel_D(置顶服务合约, 收到置顶服务规则, "1 : 1")
Rel_L(收到置顶服务规则, 置顶策略确认单, "1 : 1")